services:
  postgres:
    image: postgres:15.2
    container_name: postgres_stage
    restart: always
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    image: "ghcr.io/studio-yandex-practicum/mspp:stage"
    container_name: backend_stage
    restart: always

    depends_on:
      postgres:
        conditions: service_healthy
    volumes:
      - ./logs:/app/logs
      - static_value_stage:/app/static/
    env_file:
      - .env

  swag:
    image: linuxserver/swag:2.4.0
    container_name: swag_stage
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    volumes:
      - ./nginx_logs:/var/log/nginx
      - ./swag_nginx.conf:/config/nginx/site-confs/default.conf
      - static_value_stage:/var/html/static/
      - keys:/config/keys
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres_data_stage:
  static_value_stage:
  keys:
