name: Prod/Master Deploy

concurrency:
  group: master_deploy
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    types: [closed]

  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod_deploy
      label: stable
    secrets: inherit
