name: Stage Deploy

concurrency:
  group: stage_deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'fix/**'
      - 'refactoring/**'
  pull_request:
    branches:
      - develop
    types: [closed]


jobs:
  deploy:
    environment: stage_deploy
    uses: ./.github/workflows/test.yaml
    with:
      environment: stage_deploy
      label: stage
